title: <p align="center"> Patrick Duhirwe Nzivugira </p>

logo: "/images/picture.jpg?raw=true"

description: <p align="center">
  <a href="linkedin.com/in/patrickduhirwe">LinkedIn</a>
  </p>

  <p align="justify">
  I harness the power of cutting-edge algorithms to transform complex data into clear, actionable insights. With deep expertise in machine learning, advanced analytics, and process optimization, I deliver solutions marked by precision and efficiency, empowering organizations to make informed decisions confidently. My passion lies in bridging the gap between data science and practical outcomes, helping you unlock the full potential of your data.
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
